### ISSUE TITLE
How to produce data from origin dataset

### ISSUE THREAD

**Issue by ZQhaha** [arturjordao/WearableSensorData#3]
Hi, I would like to reproduce the USC-HAD data in LOSO, but I haven't found the code to generate it. Could you please tell me where I can get it?

**Comment by arturjordao** [comment]
Dear @ZQhaha,

Please see the closed issue #1.In this issue, I have attached a zip with the files to generate the dataset ([ExtraCodes.zip)](https://github.com/arturjordao/WearableSensorData/files/3056477/ExtraCodes.zip).

Best regards.

**Comment by ZQhaha** [comment]
Thanks a lot.
