### ISSUE TITLE
How to caculate the mean accuracy?

### ISSUE THREAD

**Issue by ZQhaha** [arturjordao/WearableSensorData#4]
Hi,
I have done some experiments on HAR, and find that the mean accuracy varies from different subjects. In your experiment, have you compute the mean value for different users or just leave the first subject for test.

**Comment by arturjordao** [comment]
Dear @ZQhaha ,

We compute the mean value for different users (i.e., mean of the mean).

Best regards,
Artur Jordão.

**Comment by ZQhaha** [comment]
Dear @arturjordao ,
Thanks for your answer. It helps me a lot. I used to be confused about this problem for a long time. Thank you!
ZQhaha.
